prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: k8s-sc  # Your correct NFS storage class
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

  ingress:
    enabled: true
    ingressClassName: nginx  # Ensure Nginx Ingress is used
    hosts:
      - "k8s01"
    paths:
      - /prom
    pathType: ImplementationSpecific

    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    tls:
      - secretName: monitoring-tls  # Ensure the TLS secret exists
        hosts:
          - k8s01  # Change this to your domain or IP
